In [2]:
import pandas as pd
import numpy as np
import matplotlib 
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from statsmodels.stats.proportion import proportions_ztest
matplotlib.rc('font', family = 'Malgun Gothic')
matplotlib.rc('axes', unicode_minus=False) # 음수표시
warnings.filterwarnings('ignore') # 경고메시지 출력 제외
import scipy.stats as stats

import matplotlib.font_manager as fm

# 한글 폰트 설정 (Windows 기준, macOS 또는 Linux는 경로가 다를 수 있습니다)
font_path = 'C:/Windows/Fonts/malgun.ttf'  # Windows의 경우
font_prop = fm.FontProperties(fname=font_path)

plt.rcParams['font.family'] = font_prop.get_name()  # 전체 설정
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 처리

In [4]:
import pandas as pd

df = pd.read_excel('Project_Data1.xlsx')

df.head()

,위치,일자,현재발전출력,수평일사량1,수평일사량2,경사일사량1,경사일사량2,외기온도1,외기온도2
0,A,2019-01-01,110.657369,126.177314,154.397648,132.259603,160.382978,14.841146,15.428378
1,A,2019-01-02,328.857233,352.846093,372.683510,382.959001,406.382636,15.685417,14.837355
2,A,2019-01-03,344.740215,388.097375,424.301904,421.362986,459.246443,15.189286,16.407851
3,A,2019-01-04,359.595589,358.813102,383.930114,380.419512,407.340175,15.935537,16.102201
4,A,2019-01-05,358.737685,319.165867,355.007110,338.567568,379.146572,16.579135,16.859500